#ifndef __UPM2388_ALGO_H
#define __UPM2388_ALGO_H __FILE__

#include "upm2388_switch.h"

#define NORMAL_TEMP_UPDATE_MS 			3000
#define HIGH_TEMP_UPDATE_MS			1000
#define WAIT_FOR_CHECK_STATUS_MS		500

#define TOTAL_NUM				3

enum thermal_zones {
	THERMAL_ZONES_INIT,			/* 0 */
	THERMAL_ZONES_M_COLD_S_COLD,		/* 1 */
	THERMAL_ZONES_M_COLD_S_COOL,		/* 2 */
	THERMAL_ZONES_M_COLD_S_NORMAL,		/* 3 */
	THERMAL_ZONES_M_COLD_S_WARM,		/* 4 */
	THERMAL_ZONES_M_COLD_S_HOT,		/* 5 */
	THERMAL_ZONES_M_COOL_S_COLD,		/* 6 */
	THERMAL_ZONES_M_COOL_S_COOL,		/* 7 */
	THERMAL_ZONES_M_COOL_S_NORMAL,		/* 8 */
	THERMAL_ZONES_M_COOL_S_WARM,		/* 9 */
	THERMAL_ZONES_M_COOL_S_HOT,		/* 10 */
	THERMAL_ZONES_M_NORMAL_S_COLD,		/* 11 */
	THERMAL_ZONES_M_NORMAL_S_COOL,		/* 12 */
	THERMAL_ZONES_M_NORMAL_S_NORMAL,	/* 13 */
	THERMAL_ZONES_M_NORMAL_S_WARM,		/* 14 */
	THERMAL_ZONES_M_NORMAL_S_HOT,		/* 15 */
	THERMAL_ZONES_M_WARM_S_COLD,		/* 16 */
	THERMAL_ZONES_M_WARM_S_COOL,		/* 17 */
	THERMAL_ZONES_M_WARM_S_NORMAL,		/* 18 */
	THERMAL_ZONES_M_WARM_S_WARM,		/* 19 */
	THERMAL_ZONES_M_WARM_S_HOT,		/* 20 */
	THERMAL_ZONES_M_HOT_S_COLD,		/* 21 */
	THERMAL_ZONES_M_HOT_S_COOL,		/* 22 */
	THERMAL_ZONES_M_HOT_S_NORMAL,		/* 23 */
	THERMAL_ZONES_M_HOT_S_WARM,		/* 24 */
	THERMAL_ZONES_M_HOT_S_HOT,		/* 25 */
	THERMAL_ZONES_INVALID,			/* 26 */
};

int upm2388_algo_init(struct upm2388 *upm);
int upm2388_algo_deinit(struct upm2388 *upm);
int upm2388_switch_enable(struct upm2388 *upm, bool enable);
#endif /* __UPM2388_ALGO_H */
