subdir-ccflags-y += -Wno-unused-but-set-variable

obj-y += devinfo/
obj-y += touchscreen/
obj-y += fingerprint/
obj-y += sensors/
obj-y += panel/
obj-y += audiopa/
obj-y += nfc/
obj-y += audiopa_aw/
obj-y += tinno_dre_mode/
