# SPDX-License-Identifier: GPL-2.0
ccflags-y += -I$(srctree)/drivers/leds/trigger
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/gpu/drm/mediatek/mediatek_v2
obj-$(CONFIG_LEDS_TRIGGER_BACKLIGHT_DRM)	+= ledtrig-backlight-drm.o
