$(warning srctree=$(srctree))
$(warning src=$(src))

ifdef CONFIG_AWINIC_SAR
	AWINIC_SAR_OBJS += ./comm/aw_sar_comm_interface.o aw_sar.o ./aw9610x/aw9610x.o ./aw9620x/aw9620x.o ./aw9620x/aw_update_fw.o ./aw963xx/aw963xx.o
endif

obj-$(CONFIG_AWINIC_SAR) += awinic_sar.o
awinic_sar-y := $(AWINIC_SAR_OBJS)

