#ifndef __TINNO_CHARGER_H__
#define __TINNO_CHARGER_H__

#include <linux/module.h>
#include <linux/power_supply.h>
#include <linux/version.h>

#define NORMAL_UPDATE_MS			5000 /*ms*/
#define SHORT_UPDATE_MS				2500 /*ms*/

#define TINNO_CHARGER_ERR_LEVEL			1
#define TINNO_CHARGER_INFO_LEVEL		2
#define TINNO_CHARGER_DBG_LEVEL			3

enum QC3P_POWER_TYPE {
	QC3P_POWER_NONE = 0,
	QC3P_POWER_15W,
	QC3P_POWER_18W,
	QC3P_POWER_27W,
	QC3P_POWER_40W,
};

enum ext_charger_type {
	//POWER_SUPPLY_TYPE_WIRELESS = 12,
	POWER_SUPPLY_TYPE_USB_QC2 = POWER_SUPPLY_TYPE_WIRELESS + 1,
	POWER_SUPPLY_TYPE_USB_QC3 = POWER_SUPPLY_TYPE_WIRELESS + 2,
	POWER_SUPPLY_TYPE_USB_QC3P = POWER_SUPPLY_TYPE_WIRELESS + 3,
	POWER_SUPPLY_TYPE_USB_NON_STD = POWER_SUPPLY_TYPE_WIRELESS + 4,
	POWER_SUPPLY_TYPE_USB_FLOAT = POWER_SUPPLY_TYPE_WIRELESS + 5,
	POWER_SUPPLY_TYPE_USB_PDC = POWER_SUPPLY_TYPE_WIRELESS + 6,
	POWER_SUPPLY_TYPE_USB_PD_DCP = POWER_SUPPLY_TYPE_WIRELESS + 7,
};

#endif /* __TINNO_CHARGER_H__ */
