ifdef CONFIG_OEM_LAMU_TOUCHSCREEN
	NVT_OBJS += nt36xxx.o \
		nt36xxx_fw_update.o \
		nt36xxx_ext_proc.o \
		nt36xxx_mp_ctrlram.o
endif

obj-$(CONFIG_OEM_LAMU_TOUCHSCREEN) += nt36672s.o
nt36672s-y := $(NVT_OBJS)

