subdir-ccflags-y += -Wno-unused-but-set-variable

ifdef CONFIG_OEM_SWITCH_CHARGER_CX2589X
	SWITCH_CHARGER_CX2589X_OBJS += cx2589x_charger.o
endif

obj-$(CONFIG_OEM_SWITCH_CHARGER_CX2589X) += cx2589x.o
cx2589x-y := $(SWITCH_CHARGER_CX2589X_OBJS)
